### PR TITLE
:arrow_up: youtube-dl tag

### PR DESCRIPTION
**Pull request by paulcarroty**
Fixes youtube playback.

### CODE REVIEW

**Review by TingPing — CHANGES_REQUESTED** [review]
As said fix the problem don't ignore it.

**Comment by paulcarroty** [comment]
Waiting for https://github.com/celluloid-player/celluloid/pull/440

**Comment by TingPing** [comment]
Your PR patch was entirely acceptable, just drop it in its own PR here. We don't need to wait.

**Comment by paulcarroty** [comment]
@TingPing, appdata was fixed in upstream. Maybe it will be better to use master here? And why this app still called `gnome-mpv`?

**Comment by TingPing** [comment]
Because Celluloid has never released...

I honestly don't understand why you won't just submit the fix already.

**Pull request merged**
